version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/healthri-basket-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/healthri-basket-api.test"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
