@healthri_basket_api_HostAddress = http://localhost:8081

# Get all baskets for a specific user
GET {{healthri_basket_api_HostAddress}}/api/v1/baskets/00000000-0000-0000-0000-000000000001
Accept: application/json

###
# Create a new basket
POST {{healthri_basket_api_HostAddress}}/api/v1/baskets/00000000-0000-0000-0000-000000000001
Content-Type: application/json

"My Sample Basket"

###
# Add single item to basket
POST {{healthri_basket_api_HostAddress}}/api/v1/baskets/{slug}/items
Content-Type: application/json

"dataset-123"

###
# Add multiple items to basket
POST {{healthri_basket_api_HostAddress}}/api/v1/baskets/{slug}/items/batch
Content-Type: application/json

[
  "dataset-123",
  "dataset-456",
  "dataset-789"
]

###
