# Docker Compose file to set up Keycloak server
# https://www.keycloak.org/getting-started/getting-started-docker

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.4
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: ["start-dev"]

volumes:
  keycloak_data: